name: CI - CD Pipeline

on : 
  push : 
    branches: [compose]
    paths-ignore:
    - 'kubernetes/deployment.yaml'

jobs :
  test :
    name : Unit Testing
    runs-on: ubuntu-latest
    steps :
      - name : Checkout code
        uses: actions/checkout@v4

      - name : Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run : npm ci

      - name : Run test
        run : npm test || echo "No tests found"

  lint :
    name : Static code analysis
    runs-on: ubuntu-latest
    steps :
      - name : Checkout code
        uses: actions/checkout@v4

      - name : Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run : npm ci

      - name : Run Lint
        run : npm run lint
  
  build :
    name : Build Stage
    runs-on: ubuntu-latest
    needs : [test,lint]
    steps :
      - name : Checkout code
        uses: actions/checkout@v4

      - name : Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run : npm ci

      - name : Run Build stage
        run : npm run build 

      - name : Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
  # docker :
  #   name : Build Docker Image
  #   runs-on: ubuntu-latest
  #   needs : [build]
  #   steps :
  #     -name : 
  

        

