name: CI - CD Pipeline

on : 
  push : 
    branches: [compose]
    paths-ignore:
    - 'kubernetes/deployment.yaml'

jobs :
  test :
    name : Unit Testing
    runs-on: ubuntu-latest
    steps :
      - name : Checkout code
        uses: actions/checkout@v4

      - name : Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run : npm ci

      - name : Run test
        run : npm test || echo "No tests found"

  lint :
    name : Static code analysis
    runs-on: ubuntu-latest
    steps :
      - name : Checkout code
        uses: actions/checkout@v4

      - name : Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run : npm ci

      - name : Run Lint
        run : npm run lint
  
  build :
    name : Build Stage
    runs-on: ubuntu-latest
    needs : [test,lint]
    steps :
      - name : Checkout code
        uses: actions/checkout@v4

      - name : Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run : npm ci

      - name : Run Build stage
        run : npm run build 

      - name : Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
  docker :
    name : Build Docker Image
    runs-on: ubuntu-latest
    needs : [build]
    outputs:
      image_tag: ${{ steps.set_output.outputs.image_tag }}
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps :
      - name : Checkout code
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/tictactoegame
          tags: type=raw,value=${{ github.ref_name }}-${{ github.sha }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile2
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Output Tag
        id: set_output
        run: echo "image_tag=$(echo ${{ github.ref_name }}-${{ github.sha }})" >> $GITHUB_OUTPUT

  update-k8s:
      name : Update k8s ddeployment
      runs-on : ubuntu-latest
      needs: [docker]
      env :
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        REPO: tictactoegame
        IMAGE_TAG: ${{ github.ref_name }}-${{ github.sha }}
      
      steps :
      - name : Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name : Add image to Deployment YAML file
        run : |
          IMAGE="${USERNAME}/${REPO}:${IMAGE_TAG}"
          sed -i "s|image: .\+|image: ${IMAGE}|g" kubernetes/deployment.yaml
          
          # Verify the change
          echo "Updated deployment to use image: ${IMAGE}"
          grep -A 1 "image:" kubernetes/deployment.yaml
      
      # Step 3: Configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Commit and push changes
        run: |
          git add kubernetes/deployment.yaml
          git commit -m "Update Kubernetes deployment with new image tag: ${{ needs.docker.outputs.image_tag }} [skip ci]" || echo "No changes to commit"
          git push  
      
